apiVersion: apps/v1
kind: Deployment
metadata:
  name: bin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bin
  template:
    metadata:
      labels:
        app: bin
    spec:
      containers:
        - image: gcr.io/starry-being-379922/binarycalculator
          name: bin
          ports:
            - containerPort: 8080
              name: bin