apiVersion: apps/v1
kind: Deployment
metadata:
  name: binarycalculator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: binarycalculator
  template:
    metadata:
      labels:
        app: binarycalculator
    spec:
      containers:
        - image: binarycalculator/binarycalculator-server
          name: binarycalculator
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_USER
              value: user
            - name: MYSQL_PASSWORD
              value: sofe3980u
            - name: MYSQL_DATABASE
              value: Table
          ports:
            - containerPort: 3306
              name: binarycalculator